version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
      nodejs: 10
    commands:
      - cd frontend && npm install
      - echo $PWD
      - cd backend && npm install
  pre_build:
    commands:
      - echo pre build phase..
  build:
    commands:
      - cd frontend && npm run build
  post_build:
    commands:
      - cd backend && npm run deploy
      - aws s3 sync frontend/build s3://$BUCKET_NAME
cache:
  paths:
    - frontend/node_modules/**
    - backend/node_modules/**
