version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
      nodejs: 10
  pre_build:
    commands:
      - cd frontend && npm install
      - cd ..
      - cd backend && npm install
      - cd ..
  build:
    commands:
      - cd ..
      - cd frontend && npm run build
      - cd ..
  post_build:
    commands:
      - cd backend && npm run deploy
      - cd ..
      - aws s3 sync frontend/build s3://$BUCKET_NAME
cache:
  paths:
    - frontend/node_modules/**
    - backend/node_modules/**
