version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
      nodejs: 10
  pre_build:
    commands:
      - make install-frontend
      - make install-backend
  build:
    commands:
      - make build-frontend
  post_build:
    commands:
      - make deploy-frontend
      - make deploy-backend
cache:
  paths:
    - frontend/node_modules/**
    - backend/node_modules/**
